export const SELECTOR_TOGETHER_TYPE_LIST = [
  { key: "", label: "--- 선택 ---" },
  { key: "study", label: "스터디" },
  { key: "sideproject", label: "사이드 프로젝트" },
  { key: "story", label: "이야기" },
];

// 온라인/ 오프라인, 서울, 강서구,
export const SELECTOR_MEAT_LIST = [
  { key: "offline", label: "오프라인" },
  { key: "online", label: "온라인" },
];

export const SELECTOR_REGION_LIST = [
  { key: "00", label: "--- 지역 ---" },

  { key: "01", label: "서울" },
  { key: "02", label: "경기" },
  { key: "03", label: "인천" },
  { key: "04", label: "강원" },

  { key: "05", label: "부산" },
  { key: "06", label: "충북" },
  { key: "07", label: "충남" },
  { key: "08", label: "세종" },

  { key: "09", label: "대전" },
  { key: "10", label: "광주" },

  { key: "11", label: "전북" },
  { key: "12", label: "전남" },

  { key: "13", label: "대구" },
  { key: "14", label: "울산" },
  { key: "15", label: "경북" },
  { key: "16", label: "경남" },
  { key: "17", label: "제주" },
];

export const SELECTOR_SUB_REGION_LIST = [
  [{ key: "00x00", label: "--- 지역 ---" }],

  // 서울
  [
    { key: "01x01", label: "전체" },
    { key: "01x02", label: "강남" },
    { key: "01x03", label: "강동" },
    { key: "01x04", label: "강북" },
    { key: "01x05", label: "강서" },
    { key: "01x06", label: "관악" },
    { key: "01x07", label: "광진" },
    { key: "01x08", label: "구로" },
    { key: "01x09", label: "금천" },
    { key: "01x10", label: "노원" },
    { key: "01x11", label: "도봉" },
    { key: "01x12", label: "동대문" },
    { key: "01x13", label: "동작" },
    { key: "01x14", label: "마포" },
    { key: "01x15", label: "서대문" },
    { key: "01x16", label: "서초" },
    { key: "01x17", label: "성동" },
    { key: "01x18", label: "성북" },
    { key: "01x19", label: "송파" },
    { key: "01x20", label: "양천" },
    { key: "01x21", label: "영등포" },
    { key: "01x22", label: "용산" },
    { key: "01x23", label: "은평" },
    { key: "01x24", label: "종로" },
    { key: "01x25", label: "중구" },
    { key: "01x26", label: "중랑" },
  ],

  // 경기
  [
    { key: "02x01", label: "전체" },
    { key: "02x02", label: "수원" },
    { key: "02x03", label: "성남" },
    { key: "02x04", label: "고양" },
    { key: "02x05", label: "용인" },
    { key: "02x06", label: "부천" },
    { key: "02x07", label: "안산" },
    { key: "02x08", label: "안양" },
    { key: "02x09", label: "남양주" },
    { key: "02x10", label: "화성" },
    { key: "02x11", label: "의정부" },
    { key: "02x12", label: "시흥" },
    { key: "02x13", label: "평택" },
    { key: "02x14", label: "광명" },
    { key: "02x15", label: "파주" },
    { key: "02x16", label: "군포" },
    { key: "02x17", label: "광주" },
    { key: "02x18", label: "김포" },
    { key: "02x19", label: "이천" },
    { key: "02x20", label: "양주" },
    { key: "02x21", label: "구리" },
    { key: "02x22", label: "오산" },
    { key: "02x23", label: "안성" },
    { key: "02x24", label: "의왕" },
    { key: "02x25", label: "하남" },
    { key: "02x26", label: "포천" },
    { key: "02x27", label: "동두천" },
    { key: "02x28", label: "과천" },
    { key: "02x29", label: "여주" },
    { key: "02x30", label: "양평" },
    { key: "02x31", label: "가평" },
    { key: "02x32", label: "연천" },
  ],

  // 인천
  [
    { key: "03x01", label: "전체" },
    { key: "03x02", label: "중구" },
    { key: "03x03", label: "동구" },
    { key: "03x04", label: "미추홀" },
    { key: "03x05", label: "연수" },
    { key: "03x06", label: "남동" },
    { key: "03x07", label: "부평" },
    { key: "03x08", label: "계양" },
    { key: "03x09", label: "서구" },
    { key: "03x10", label: "강화" },
    { key: "03x11", label: "옹진" },
  ],

  // 강원
  [
    { key: "04x01", label: "전체" },
    { key: "04x02", label: "춘천" },
    { key: "04x03", label: "인제" },
    { key: "04x04", label: "양구" },
    { key: "04x05", label: "회양" },
    { key: "04x06", label: "통천" },
    { key: "04x07", label: "고성" },
    { key: "04x08", label: "양양" },
    { key: "04x09", label: "강릉" },
    { key: "04x10", label: "속초" },
    { key: "04x11", label: "삼척" },
    { key: "04x12", label: "울진" },
    { key: "04x13", label: "정선" },
    { key: "04x14", label: "평창" },
    { key: "04x15", label: "영월" },
    { key: "04x16", label: "원주" },
    { key: "04x17", label: "횡성" },
    { key: "04x18", label: "홍천" },
    { key: "04x19", label: "화천" },
    { key: "04x20", label: "김화" },
    { key: "04x21", label: "철원" },
    { key: "04x22", label: "평강" },
    { key: "04x23", label: "이천" },
  ],

  // 부산
  [
    { key: "05x01", label: "전체" },
    { key: "05x02", label: "중구" },
    { key: "05x03", label: "서구" },
    { key: "05x04", label: "동구" },
    { key: "05x05", label: "영도" },
    { key: "05x06", label: "진구" },
    { key: "05x07", label: "동래" },
    { key: "05x08", label: "남구" },
    { key: "05x09", label: "북구" },
    { key: "05x10", label: "강서" },
    { key: "05x11", label: "해운대" },
    { key: "05x12", label: "사하" },
    { key: "05x13", label: "금정" },
    { key: "05x14", label: "연제" },
    { key: "05x15", label: "수영" },
    { key: "05x16", label: "사상" },
    { key: "05x17", label: "기장" },
  ],

  // 충북
  [
    { key: "06x01", label: "전체" },
    { key: "06x02", label: "청주" },
    { key: "06x03", label: "충주" },
    { key: "06x04", label: "제천" },
    { key: "06x05", label: "보은" },
    { key: "06x06", label: "옥천" },
    { key: "06x07", label: "영동" },
    { key: "06x08", label: "증평" },
    { key: "06x09", label: "진천" },
    { key: "06x10", label: "괴산" },
    { key: "06x11", label: "음성" },
    { key: "06x12", label: "단양" },
  ],

  // 충남
  [
    { key: "07x01", label: "전체" },
    { key: "07x02", label: "천안" },
    { key: "07x03", label: "공주" },
    { key: "07x04", label: "보령" },
    { key: "07x05", label: "아산" },
    { key: "07x06", label: "서산" },
    { key: "07x07", label: "논산" },
    { key: "07x08", label: "계룡" },
    { key: "07x09", label: "당진" },
    { key: "07x10", label: "금산" },
    { key: "07x11", label: "부여" },
    { key: "07x12", label: "서천" },
    { key: "07x13", label: "청양" },
    { key: "07x14", label: "홍성" },
    { key: "07x15", label: "예산" },
    { key: "07x16", label: "태안" },
  ],

  // 세종
  [
    { key: "08x01", label: "전체" },
    { key: "08x02", label: "조치원" },
    { key: "08x03", label: "연기" },
    { key: "08x04", label: "연동" },
    { key: "08x05", label: "부강" },
    { key: "08x06", label: "금남" },
    { key: "08x07", label: "장군" },
    { key: "08x08", label: "연서" },
    { key: "08x09", label: "전의" },
    { key: "08x10", label: "전동" },
    { key: "08x11", label: "소정" },
    { key: "08x12", label: "한솔" },
    { key: "08x13", label: "새롬" },
    { key: "08x14", label: "도담" },
    { key: "08x15", label: "아름" },
    { key: "08x16", label: "종촌" },
    { key: "08x17", label: "고운" },
    { key: "08x18", label: "소담" },
    { key: "08x19", label: "보람" },
    { key: "08x20", label: "대평" },
    { key: "08x21", label: "다정" },
  ],

  // 대전
  [
    { key: "09x01", label: "전체" },
    { key: "09x02", label: "동구" },
    { key: "09x03", label: "중구" },
    { key: "09x04", label: "서구" },
    { key: "09x05", label: "유성" },
    { key: "09x06", label: "대덕" },
  ],

  // 광주
  [
    { key: "10x01", label: "전체" },
    { key: "10x02", label: "동구" },
    { key: "10x03", label: "서구" },
    { key: "10x04", label: "남구" },
    { key: "10x05", label: "북구" },
    { key: "10x06", label: "광산" },
  ],

  // 전북
  [
    { key: "11x01", label: "전체" },
    { key: "11x02", label: "전주" },
    { key: "11x03", label: "익산" },
    { key: "11x04", label: "군산" },
    { key: "11x05", label: "정읍" },
    { key: "11x06", label: "남원" },
    { key: "11x07", label: "김제" },
    { key: "11x08", label: "완주" },
    { key: "11x09", label: "고창" },
    { key: "11x10", label: "부안" },
    { key: "11x11", label: "임실" },
    { key: "11x12", label: "순창" },
    { key: "11x13", label: "진안" },
    { key: "11x14", label: "무주" },
    { key: "11x15", label: "장수" },
  ],

  // 전남
  [
    { key: "12x01", label: "전체" },
    { key: "12x02", label: "목포" },
    { key: "12x03", label: "여수" },
    { key: "12x04", label: "순천" },
    { key: "12x05", label: "나주" },
    { key: "12x06", label: "광양" },
    { key: "12x07", label: "담양" },
    { key: "12x08", label: "곡성" },
    { key: "12x09", label: "구례" },
    { key: "12x10", label: "고흥" },
    { key: "12x11", label: "보성" },
    { key: "12x12", label: "화순" },
    { key: "12x13", label: "장흥" },
    { key: "12x14", label: "강진" },
    { key: "12x15", label: "해남" },
    { key: "12x16", label: "영암" },
    { key: "12x17", label: "무안" },
    { key: "12x18", label: "함평" },
    { key: "12x19", label: "영광" },
    { key: "12x20", label: "장성" },
    { key: "12x21", label: "완도" },
    { key: "12x22", label: "진도" },
    { key: "12x23", label: "신안" },
  ],

  // 대구
  [
    { key: "13x01", label: "전체" },
    { key: "13x02", label: "중구" },
    { key: "13x03", label: "동구" },
    { key: "13x04", label: "서구" },
    { key: "13x05", label: "남구" },
    { key: "13x06", label: "북구" },
    { key: "13x07", label: "수성" },
    { key: "13x08", label: "달서" },
    { key: "13x09", label: "달성" },
  ],

  // 울산
  [
    { key: "14x01", label: "전체" },
    { key: "14x02", label: "중구" },
    { key: "14x03", label: "남구" },
    { key: "14x04", label: "동구" },
    { key: "14x05", label: "북구" },
    { key: "14x06", label: "울주군" },
  ],

  // 경북
  [
    { key: "15x01", label: "전체" },
    { key: "15x02", label: "포항" },
    { key: "15x03", label: "경주" },
    { key: "15x04", label: "김천" },
    { key: "15x05", label: "안동" },
    { key: "15x06", label: "구미" },
    { key: "15x07", label: "영주" },
    { key: "15x08", label: "영천" },
    { key: "15x09", label: "상주" },
    { key: "15x10", label: "문경" },
    { key: "15x11", label: "경산" },
    { key: "15x12", label: "군위" },
    { key: "15x13", label: "의성" },
    { key: "15x14", label: "청송" },
    { key: "15x15", label: "영양" },
    { key: "15x16", label: "영덕" },
    { key: "15x17", label: "청도" },
    { key: "15x18", label: "고령" },
    { key: "15x19", label: "성주" },
    { key: "15x20", label: "칠곡" },
    { key: "15x21", label: "예천" },
    { key: "15x22", label: "봉화" },
    { key: "15x23", label: "울진" },
    { key: "15x24", label: "울릉" },
  ],

  // 경남
  [
    { key: "16x01", label: "전체" },
    { key: "16x02", label: "창원" },
    { key: "16x03", label: "김해" },
    { key: "16x04", label: "양산" },
    { key: "16x05", label: "진주" },
    { key: "16x06", label: "거제" },
    { key: "16x07", label: "통영" },
    { key: "16x08", label: "사천" },
    { key: "16x09", label: "밀양" },
    { key: "16x10", label: "함안" },
    { key: "16x11", label: "거창" },
    { key: "16x12", label: "창녕" },
    { key: "16x13", label: "고성" },
    { key: "16x14", label: "하동" },
    { key: "16x15", label: "합천" },
    { key: "16x16", label: "남해" },
    { key: "16x17", label: "함양" },
    { key: "16x18", label: "산청" },
    { key: "16x19", label: "의령" },
  ],

  // 제주
  [
    { key: "17x01", label: "전체" },
    { key: "17x02", label: "애월" },
    { key: "17x03", label: "한림" },
    { key: "17x04", label: "한경" },
    { key: "17x05", label: "대정" },
    { key: "17x06", label: "안덕" },
    { key: "17x07", label: "서귀포" },
    { key: "17x08", label: "남원" },
    { key: "17x09", label: "표선" },
    { key: "17x10", label: "성산" },
  ],
];

/**
 * 기획 디자인 마켓팅 개발 기타
 */
export const SELECTOR_RECRUIT_TYPE = [
  { key: "no", label: "--- 분야 ---" },
  { key: "dev", label: "개발" },
  { key: "plan", label: "기획" },
  { key: "design", label: "디자인" },
  { key: "margket", label: "마켓팅" },
  { key: "excercise", label: "운동" },
  { key: "write", label: "글쓰기" },
  { key: "invest", label: "경제/투자" },
  { key: "etc", label: "악기" },
  { key: "etc", label: "기타" },
];

export const SELECTOR_RECRUIT_SUB_TYPE = [
  [{ key: "no", label: "--- 분야 ---" }],
  [
    { key: "total", label: "전체" },
    { key: "frontend", label: "프론트엔드" },
    { key: "backend", label: "백엔드" },
    { key: "android", label: "안드로이드" },
    { key: "ios", label: "ios" },
    { key: "data", label: "데이터" },
    { key: "ai", label: "인공지능" },
  ],
  [{ key: "total", label: "전체" }],
  [
    { key: "total", label: "전체" },
    { key: "graphic", label: "그래픽 디자인" },
    { key: "uiux", label: "UI/UX 디자인" },
    { key: "char", label: "캐릭터 디자인" },
    { key: "product", label: "상품 디자인" },
  ],
  [{ key: "total", label: "전체" }],
  [{ key: "total", label: "전체" }],
  [{ key: "total", label: "전체" }],
  [{ key: "total", label: "전체" }],
  [{ key: "total", label: "전체" }],
  [{ key: "total", label: "전체" }],
];
